[package]
edition = "2018"
name = "ors-kernel"
version = "0.1.0"

[dependencies]
derive-new = {version = "0.5", default-features = false}
heapless = "0.7"
log = {version = "0.4", default-features = false}
modular-bitfield = "0.11"
ors-common = {path = "../ors-common"}
static_assertions = "1"
